
name: Build Mac UE.5.0

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/gitignore'
  workflow_dispatch:

jobs:
  build-mac-50:
    runs-on: [ self-hosted, macOS, ARM64, m1-1317 ]
    steps:
    - uses: actions/checkout@v2
    - name: git-update-dependecies
      run: git submodule update --init --recursive
    - name: Find NDK SHA
      run: |
        INWORLD_NDK_SHA=$(git submodule status | cut -d " " -f 2)
        echo $INWORLD_NDK_SHA
        echo "INWORLD_NDK_SHA=$INWORLD_NDK_SHA" >> $GITHUB_ENV
    - uses: actions/cache/restore@v3
      id: ndk-cache
      with:
        path: InworldAI\inworld-ndk\build\Package
        key: ${{ runner.OS }}-ndk-cache-Mac-${{ env.INWORLD_NDK_SHA }}
    - name: Build NDK
      shell: bash
      if: steps.ndk-cache.outputs.cache-hit != 'true'
      run: |
        echo "Build NDK goes here"
    - run: mkdir -p TestInworldFPS 
    - uses: actions/checkout@v2
      with:
        ref: 'TestInworldFPS'
        path: 'TestInworldFPS'
    - name: Copy Plugins & Remove Assets
      shell: bash
      run: |
          rm -rf "InworldAI/Content"
          rm -rf "TestInworldFPS/TestInworldFPS/Plugins/InworldAI"
          rm -rf "TestInworldFPS/TestInworldFPS/Plugins/InworldMetahuman"
          rm -rf "TestInworldFPS/TestInworldFPS/Plugins/InworldReadyPlayerMe"
          mkdir "TestInworldFPS/TestInworldFPS/Plugins"
          cp -r "InworldAI" "TestInworldFPS/TestInworldFPS/Plugins"
          cp -r "InworldMetahuman" "TestInworldFPS/TestInworldFPS/Plugins"
          cp -r "InworldReadyPlayerMe" "TestInworldFPS/TestInworldFPS/Plugins"
    - name: BuildEditor-Mac-50
      shell: bash
      run: |
          sh "/Users/Shared/Epic Games/UE_5.1/Engine/Build/BatchFiles/RunUAT.sh" > BuildGameLog.txt BuildEditor -project="$PWD/TestInworldFPS/TestInworldFPS/TestInworldFPS.uproject" -platform=Mac  -notools -configuration=Development+Shipping
          cat BuildGameLog.txt
          if (grep -Fxq "BUILD SUCCESSFUL" BuildGameLog.txt)
          then
              exit 0
          fi
          exit 1
    - name: BuildGame-Mac-50
      shell: bash
      run: |
          sh "/Users/Shared/Epic Games/UE_5.1/Engine/Build/BatchFiles/RunUAT.sh" > BuildGameLog.txt BuildGame -project="$PWD/TestInworldFPS/TestInworldFPS/TestInworldFPS.uproject" -platform=Mac  -notools -configuration=Development+Shipping
          cat BuildGameLog.txt
          if (grep -Fxq "BUILD SUCCESSFUL" BuildGameLog.txt)
          then
              exit 0
          fi
          exit 1

         
